apiVersion: v2
name: docutag
description: AI-Powered Web Content Processing Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - docutag
  - web-scraping
  - ai
  - text-analysis
  - kubernetes
home: https://github.com/docutag/platform
sources:
  - https://github.com/docutag/platform
maintainers:
  - name: DocuTag Team
    email: team@docutag.io
dependencies:
  - name: redis
    version: 18.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 13.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
