services:
  # Text Analyzer Service
  textanalyzer:
    image: localhost/purpletab-textanalyzer:latest
    build:
      context: ./apps/textanalyzer
      dockerfile: Dockerfile
    container_name: purpletab-textanalyzer
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/textanalyzer.db
      - USE_OLLAMA=true
      - OLLAMA_URL=http://100.64.0.2:11434
      - OLLAMA_MODEL=gemma3:12b
    volumes:
      - textanalyzer-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - purpletab-network

  # Scraper Service
  scraper:
    image: localhost/purpletab-scraper:latest
    build:
      context: ./apps/scraper
      dockerfile: Dockerfile
    container_name: purpletab-scraper
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/scraper.db
      - OLLAMA_URL=http://100.64.0.2:11434
      - OLLAMA_MODEL=gemma3:12b
      # - OLLAMA_VISION_MODEL=gemma3.12b
    volumes:
      - scraper-data:/app/data
    command: [
      "./scraper-api",
    ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - purpletab-network

  # Scheduler Service
  scheduler:
    image: localhost/purpletab-scheduler:latest
    build:
      context: ./apps/scheduler
      dockerfile: Dockerfile
    container_name: purpletab-scheduler
    ports:
      - "8083:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/scheduler.db
      - CONTROLLER_DB_PATH=/app/data/controller/controller.db
      - SCRAPER_URL=http://scraper:8080
    volumes:
      - scheduler-data:/app/data
      - controller-data:/app/data/controller:ro  # Read-only access to controller DB
    restart: unless-stopped
    depends_on:
      controller:
        condition: service_healthy
      scraper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - purpletab-network

  # Controller Service
  controller:
    image: localhost/purpletab-controller:latest
    build:
      context: ./apps/controller
      dockerfile: Dockerfile
    container_name: purpletab-controller
    ports:
      - "8080:8080"
    environment:
      # Service URLs - internal network references
      - SCRAPER_BASE_URL=http://scraper:8080
      - TEXTANALYZER_BASE_URL=http://textanalyzer:8080
      - SCHEDULER_BASE_URL=http://scheduler:8080
      # Controller configuration
      - CONTROLLER_PORT=8080
      - DATABASE_PATH=/app/data/controller.db
      # Mock data generation (set to "true" to generate 14 days of test data)
      - GENERATE_MOCK_DATA=true
    volumes:
      - controller-data:/app/data
    restart: unless-stopped
    depends_on:
      scraper:
        condition: service_healthy
      textanalyzer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - purpletab-network

  # Web UI Service
  web:
    image: localhost/purpletab-web:latest
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: purpletab-web
    ports:
      - "3000:80"
    environment:
      # API URL for frontend (set at build time in Vite)
      - CONTROLLER_API_URL=http://controller:8080
    restart: unless-stopped
    depends_on:
      controller:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - purpletab-network

volumes:
  controller-data:
    driver: local
  scraper-data:
    driver: local
  textanalyzer-data:
    driver: local
  scheduler-data:
    driver: local

networks:
  purpletab-network:
    name: purpletab-network
    driver: bridge