services:
  # Text Analyzer Service
  textanalyzer:
    build:
      context: ./apps/textanalyzer
      dockerfile: Dockerfile
    container_name: purplepill-textanalyzer
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/textanalyzer.db
      - USE_OLLAMA=true
      - OLLAMA_URL=http://100.64.0.2:11434
      - OLLAMA_MODEL=gpt-oss:20b
    volumes:
      - textanalyzer-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - purplepill-network

  # Scraper Service
  scraper:
    build:
      context: ./apps/scraper
      dockerfile: Dockerfile
    container_name: purplepill-scraper
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/scraper.db
      - OLLAMA_URL=http://100.64.0.2:11434
      - OLLAMA_MODEL=gpt-oss:20b
    volumes:
      - scraper-data:/app/data
    command: [
      "./scraper-api",
    ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - purplepill-network

  # Controller Service
  controller:
    build:
      context: ./apps/controller
      dockerfile: Dockerfile
    container_name: purplepill-controller
    ports:
      - "8080:8080"
    environment:
      # Service URLs - internal network references
      - SCRAPER_BASE_URL=http://scraper:8080
      - TEXTANALYZER_BASE_URL=http://textanalyzer:8080
      # Controller configuration
      - CONTROLLER_PORT=8080
      - DATABASE_PATH=/app/data/controller.db
    volumes:
      - controller-data:/app/data
    restart: unless-stopped
    depends_on:
      scraper:
        condition: service_healthy
      textanalyzer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - purplepill-network

volumes:
  controller-data:
    driver: local
  scraper-data:
    driver: local
  textanalyzer-data:
    driver: local

networks:
  purplepill-network:
    name: purplepill-network
    driver: bridge