version: '3.8'

# Build configuration for staging images
# Usage: docker-compose -f docker-compose.build-staging.yml build

services:
  textanalyzer:
    image: docutag-textanalyzer:staging
    build:
      context: ./apps/textanalyzer
      dockerfile: Dockerfile

  scraper:
    image: docutag-scraper:staging
    build:
      context: ./apps/scraper
      dockerfile: Dockerfile

  controller:
    image: docutag-controller:staging
    build:
      context: ./apps/controller
      dockerfile: Dockerfile

  scheduler:
    image: docutag-scheduler:staging
    build:
      context: ./apps/scheduler
      dockerfile: Dockerfile

  web:
    image: docutag-web:staging
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        # Build-time environment variables for React
        # Note: Vite requires VITE_ prefix for env vars to be exposed to client
        - VITE_PUBLIC_URL_BASE=https://docutag.honker
        - VITE_CONTROLLER_API_URL=/api
