server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # No filters - scrape all containers, then filter by relabel_configs

    relabel_configs:
      # Only scrape containers with app=docutab label
      - source_labels: ['__meta_docker_container_label_app']
        regex: 'docutab'
        action: keep

      # Add app label
      - source_labels: ['__meta_docker_container_label_app']
        target_label: 'app'

      # Add app.type label (backend/frontend)
      - source_labels: ['__meta_docker_container_label_app_type']
        target_label: 'app_type'

      # Use container name as the main identifier
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
        regex: '/(.*)'
        replacement: '${1}'

      # Extract service name from container name (e.g., docutab-controller -> controller)
      - source_labels: ['__meta_docker_container_name']
        target_label: 'service'
        regex: '/docutab-(.*)'
        replacement: '${1}'

      # Add environment label
      - target_label: 'environment'
        replacement: 'staging'

      # Add compose project label
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'compose_project'

      # Add compose service label
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'

      # Extract log stream (stdout/stderr)
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
