{{- if .Values.textanalyzer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docutag.fullname" . }}-textanalyzer
  labels:
    {{- include "docutag.componentLabels" (dict "component" "textanalyzer" "type" "backend" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.textanalyzer.service.type }}
  ports:
  - port: {{ .Values.textanalyzer.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "docutag.componentSelectorLabels" (dict "component" "textanalyzer" "context" .) | nindent 4 }}
{{- end }}
