{{- if .Values.blueGreen.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "docutag.fullname" . }}-health-checks
  labels:
    {{- include "docutag.labels" . | nindent 4 }}
spec:
  metrics:
  # Controller health check
  - name: controller-health
    initialDelay: {{ .Values.blueGreen.analysis.healthCheckDelay | default "10s" }}
    interval: 10s
    count: {{ .Values.blueGreen.analysis.healthCheckCount | default 5 }}
    successCondition: result == "healthy"
    failureLimit: 3
    provider:
      web:
        url: http://{{ include "docutag.fullname" . }}-controller-preview:8080/health
        jsonPath: "{$.status}"
        timeoutSeconds: 5

  # Web UI health check
  - name: web-health
    initialDelay: {{ .Values.blueGreen.analysis.healthCheckDelay | default "10s" }}
    interval: 10s
    count: {{ .Values.blueGreen.analysis.healthCheckCount | default 5 }}
    successCondition: result.statusCode == "200"
    failureLimit: 3
    provider:
      web:
        url: http://{{ include "docutag.fullname" . }}-web-preview:80/
        timeoutSeconds: 5

  {{- if .Values.blueGreen.analysis.prometheusEnabled }}
  # Error rate check (requires Prometheus)
  - name: error-rate
    initialDelay: {{ .Values.blueGreen.analysis.metricsDelay | default "60s" }}
    interval: 30s
    count: {{ .Values.blueGreen.analysis.metricsCount | default 3 }}
    successCondition: result < {{ .Values.blueGreen.analysis.errorRateThreshold | default 0.05 }}
    failureLimit: 2
    provider:
      prometheus:
        address: {{ .Values.blueGreen.analysis.prometheusAddress | default "http://prometheus:9090" }}
        query: |
          sum(rate(http_requests_total{namespace="{{ .Release.Namespace }}",status=~"5.."}[5m]))
          /
          sum(rate(http_requests_total{namespace="{{ .Release.Namespace }}"}[5m]))

  # Response time check (requires Prometheus)
  - name: response-time
    initialDelay: {{ .Values.blueGreen.analysis.metricsDelay | default "60s" }}
    interval: 30s
    count: {{ .Values.blueGreen.analysis.metricsCount | default 3 }}
    successCondition: result < {{ .Values.blueGreen.analysis.responseTimeThreshold | default 500 }}
    failureLimit: 2
    provider:
      prometheus:
        address: {{ .Values.blueGreen.analysis.prometheusAddress | default "http://prometheus:9090" }}
        query: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_milliseconds_bucket{namespace="{{ .Release.Namespace }}"}[5m])) by (le)
          )
  {{- end }}
{{- end }}
