name: Coverage Badges

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [controller, scraper, textanalyzer, scheduler]

    environment: CI
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.9'

      - name: Install dependencies
        working-directory: apps/${{ matrix.service }}
        run: go mod download

      - name: Run tests with coverage
        working-directory: apps/${{ matrix.service }}
        run: |
          go test -v -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out -o coverage.txt

      - name: Extract coverage percentage
        working-directory: apps/${{ matrix.service }}
        id: coverage
        run: |
          COVERAGE=$(grep total coverage.txt | awk '{print $3}')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Coverage for ${{ matrix.service }}: $COVERAGE"

      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: YOUR_GIST_ID_HERE  # Create a gist and put its ID here
          filename: purpletab-${{ matrix.service }}-coverage.json
          label: coverage
          message: ${{ steps.coverage.outputs.coverage }}
          color: >-
            ${{
              steps.coverage.outputs.coverage >= '80' && 'brightgreen' ||
              steps.coverage.outputs.coverage >= '60' && 'yellow' ||
              'red'
            }}

  web-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    environment: CI
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage -- --run

      - name: Extract coverage percentage
        id: coverage
        run: |
          # Extract coverage from vitest/jest output
          COVERAGE=$(grep -oP 'All files\s+\|\s+\K[\d.]+' coverage/coverage-summary.txt || echo "0")
          echo "coverage=$COVERAGE%" >> $GITHUB_OUTPUT
          echo "Coverage for web: $COVERAGE%"

      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: YOUR_GIST_ID_HERE
          filename: purpletab-web-coverage.json
          label: coverage
          message: ${{ steps.coverage.outputs.coverage }}
          color: >-
            ${{
              steps.coverage.outputs.coverage >= '80' && 'brightgreen' ||
              steps.coverage.outputs.coverage >= '60' && 'yellow' ||
              'red'
            }}
