name: Test Scraper

on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/scraper/**'
    branches: [ main, master, develop ]
  pull_request:
    paths:
      - 'apps/scraper/**'
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/scraper

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.9'
          cache-dependency-path: apps/scraper/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: make test

      - name: Run tests with coverage
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          files: ./apps/scraper/coverage.txt
          flags: scraper
          name: scraper-coverage
