name: Test Web

on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/web/**'
    branches: [ main, master, develop ]
  pull_request:
    paths:
      - 'apps/web/**'
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    strategy:
      matrix:
        node-version: ['20', '24']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint code (if configured)
        run: npm run lint --if-present
        continue-on-error: true

      - name: Type check (if configured)
        run: npm run type-check --if-present
        continue-on-error: true

      - name: Run tests
        run: npm test

      - name: Run tracing tests
        run: npm test -- tracing.test.js --run

      - name: Run Timeline regression tests
        run: |
          echo "Running Timeline selection stability tests..."
          npm test -- Timeline.selectionStability.test.jsx --run
          echo "Running Timeline regression suite..."
          npm test -- Timeline.regressionSuite.test.jsx --run
          echo "✅ All Timeline regression tests passed!"

      - name: Run tests with coverage
        run: npm run test:coverage --if-present
        continue-on-error: true

      - name: Build application
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright E2E tests
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-node-${{ matrix.node-version }}
          path: apps/web/playwright-report/
          retention-days: 30

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '24'
        with:
          files: ./apps/web/coverage/coverage-final.json
          flags: web
          name: web-coverage
        continue-on-error: true

  # Full browser matrix test - only runs on main/master branch
  e2e-full-browsers:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Install Playwright Browsers (all browsers)
        run: npx playwright install --with-deps

      - name: Run Playwright E2E tests (all browsers)
        run: npm run test:e2e
        env:
          CI_FULL_BROWSERS: 'true'

      - name: Upload Playwright report (full browsers)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-full-browsers
          path: apps/web/playwright-report/
          retention-days: 30
