apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    isDefault: true
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id[\"=:]\\s?([0-9a-f]+)"
          name: TraceID
          url: "$${__value.raw}"
        - datasourceUid: tempo
          matcherRegex: "traceID[\"=:]\\s?([0-9a-f]+)"
          name: TraceID
          url: "$${__value.raw}"
